Worked merge rover fork and drone fork together as well as have the the option to select rover or drone in the configuration file. Fixed the issue with ros hanging the scripts in start up and shut down. Included is also some basic bug fixes and missing items that should have been in the scripts orginally.

diff --git a/gcstart b/gcstart
--- a/gcstart
+++ b/gcstart
@@ -5,21 +5,21 @@
 
 ./systemcheck gcstart
 
-if [ $? -ne 0 ];
+if [ $? -ne 0 ]; #checking return value of system check exit state (1 or 0)
 then
   exit 1
 fi
 
-# Save the start date/time for gcstop and the server and aircraft start scripts
+# Save the start date/time for gcstop and the server and VEHICLE start scripts
 DATETIME=`date +%Y-%m-%d-%H-%M`
-echo $DATETIME >missionstartdt
+echo $DATETIME >missionstartdt #creates file missionstartdt for source later
 
-# Start ROS on aircraft
-echo "Initializing aircraft..."
-scp missionstartdt $AIRCRAFT_USER@$AIRCRAFT_IP:missionstartdt >/dev/null
-scp config.sh $AIRCRAFT_USER@$AIRCRAFT_IP:config.sh >/dev/null
-scp rosstart.sh $AIRCRAFT_USER@$AIRCRAFT_IP:rosstart.sh >/dev/null
-ssh $AIRCRAFT_USER@$AIRCRAFT_IP "./rosstart.sh" 
+# Start ROS on VEHICLE
+echo "Initializing VEHICLE..."
+scp missionstartdt $VEHICLE_USER@$VEHICLE_IP:missionstartdt >/dev/null
+scp config.sh $VEHICLE_USER@$VEHICLE_IP:config.sh >/dev/null
+scp rosstart.sh $VEHICLE_USER@$VEHICLE_IP:start_$VEHICLE_TYPE.sh >/dev/null
+ssh $VEHICLE_USER@$VEHICLE_IP "./start_$VEHICLE_TYPE.sh" #rosstart.sh was replaced by start_$VEHICLE_TYPE.sh (rover or drone as set in config.sh)
 sleep 2
 echo "${green}Done.${reset}"
 
@@ -30,7 +30,7 @@ ssh $SERVER_USER@$SERVER_IP "rm *.bag *.mp4 >/dev/null 2>/dev/null" >/dev/null
 scp missionstartdt $SERVER_USER@$SERVER_IP:missionstartdt >/dev/null
 scp config.sh $SERVER_USER@$SERVER_IP:config.sh >/dev/null
 scp serverstart.sh $SERVER_USER@$SERVER_IP:serverstart.sh >/dev/null
-
+ssh $SERVER_USER@$SERVER_IP "./serverstart_$VEHICLE_TYPE.sh" ### this was completely missing from the origional code
 
 # Start QGC in background
 nohup ./QGroundControl.AppImage >/dev/null 2>/dev/null &
diff --git a/systemcheck b/systemcheck
--- a/systemcheck
+++ b/systemcheck
@@ -4,16 +4,16 @@
 
 . ./config.sh
 
-# Ensure aircraft is powered up and on the network.
-if ! ping -c 1 -W 3 $AIRCRAFT_IP &>/dev/null
+# Ensure VEHICLE is powered up and on the network.
+if ! ping -c 1 -W 3 $VEHICLE_IP &>/dev/null
 then
   echo
-  echo "${red}Cannot communicate with aircraft!${reset}"
+  echo "${red}Cannot communicate with VEHICLE!${reset}"
   echo
   echo "Please check the following and try again:"
-  echo "1. Is the aircraft powered on?"
+  echo "1. Is the VEHICLE powered on?"
   echo "2. Is it connected to the network?"
-  echo "3. Is the AIRCRAFT_IP address correct in config.sh?"
+  echo "3. Is the VEHICLE_IP address correct in config.sh?"
   echo
   echo
   echo "Press ENTER to exit this window."
@@ -21,7 +21,7 @@ then
   exit 1
 else
   echo
-  echo "${green}Aircraft is powered on and connected to the network.${reset}"
+  echo "${green}VEHICLE is powered on and connected to the network.${reset}"
 fi
 
 # Ensure server is powered up and on the network.
@@ -58,13 +58,13 @@ then
   exit 1
 fi
 
-# Ensure the AIRCRAFT_USER is correct.
-if ! ssh $AIRCRAFT_USER@$AIRCRAFT_IP "ls" >/dev/null
+# Ensure the VEHICLE_USER is correct.
+if ! ssh $VEHICLE_USER@$VEHICLE_IP "ls" >/dev/null
 then
   echo
-  echo "${red}Unable to log in to aircraft!${reset}"
+  echo "${red}Unable to log in to VEHICLE!${reset}"
   echo
-  echo "Please check the AIRCRAFT_USER line in config.sh and try again."
+  echo "Please check the VEHICLE_USER line in config.sh and try again."
   echo
   echo
   echo "Press ENTER to exit this window."
